### ISSUE TITLE
quantity in L2Event

### ISSUE THREAD

**Issue by crazybits** [aux-exchange/aux-exchange#300]
referring to the [code]( https://github.com/aux-exchange/aux-exchange/blob/main/aptos/api/aux-ts/src/clob/core/query.ts#L266-L273) , the quantity in L2Event is base coin in both ask and bid order,  is it correct?

**Comment by fardream** [comment]
> referring to the [code](https://github.com/aux-exchange/aux-exchange/blob/main/aptos/api/aux-ts/src/clob/core/query.ts#L266-L273) , the quantity in L2Event is base coin in both ask and bid order, is it correct?

Yes, this is correct. This is inline with stock market, where the quantity is generally referring to the quantity of the base instrument - the stock you are buying/selling.
