### ISSUE TITLE
add liquidity coin ratio is wrong

### ISSUE THREAD

**Issue by fardream** [aux-exchange/aux-exchange#320]
See below screenshot. APT is ~0.1, and USDC is 506. So to deposit 1 APT, the corresponding USDC should be ~5062.
However, the page calculates ~465

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/2446507/205418358-51cb7410-1751-42e1-b200-c9ca56d3faa9.png">

When click through the add liquidity button, error pops up saying not enough coins.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/2446507/205418439-1b0ab43d-96bc-46d6-bacb-b429cd534c2a.png">

**Comment by fardream** [comment]
> This should be fixed now, right? @lidatong

doesn't look like so. On mainnet beta

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/2446507/206285009-fb0a2a98-6c1c-4329-8c8e-41484da32c60.png">

**Comment by lidatong** [comment]
it's the UI that still needs to be updated to use the new spot price endpoints

**Comment by lidatong** [comment]
resolved
